export const lsButton = [
  { _id: 'clear', label: 'clear', cClass: 'merce-3-row' },
  { _id: '/', label: '/' },
  { _id: '7', label: '7' },
  { _id: '8', label: '8' },
  { _id: '9', label: '9' },
  { _id: '-', label: '-' },
  { _id: '4', label: '4' },
  { _id: '5', label: '5' },
  { _id: '6', label: '6' },
  { _id: '+', label: '+' },
  { _id: '1', label: '1' },
  { _id: '2', label: '2' },
  { _id: '3', label: '3' },
  { _id: '=', label: '=' },
]